#!/bin/bash

# Created by Matthew Hull on 5/1/19

# This script will grab graphs from LibreNMS and email them as inline images or attachments.
# Requires: wget, inkscape, mailx

# Set the needed variables
siteURL="https://librenms.domain.com"
currentDate="$(date +"%Y-%m-%d")"
sendFrom="librenms@domain.com"
sendTo="email1@domain.com,email2@domain.com"
subjectLine="LibreNMS Report $currentDate"
backupLocation="/home/username/Backup/Graphs"
adminUser="username"
includeAttachments=false

getGraphs()
{    

    # getGraphs(Port#, PortType, FileNamePrefix, GraphTitle)

    # Get the SVG file from the Libre NMS server and convert it to a PNG
    wget "$siteURL/graph.php?id=$1&type=$2&legend=yes&height=150&width=500&from=end-24h" -O tmp.svg
    inkscape -b "#FFFFFF" tmp.svg -e $3-$currentDate.png
    rm tmp.svg

    # Copy the PNG to the website and the backup location
    cp $3-$currentDate.png $backupLocation
    cp $3-$currentDate.png /opt/librenms/html/graphs

    # Fix ownership of the new file
    chown librenms /opt/librenms/html/graphs/$3-$currentDate.png
    chgrp librenms /opt/librenms/html/graphs/$3-$currentDate.png
    chown $adminUser $backupLocation/$3-$currentDate.png
    chgrp $adminUser $backupLocation/$3-$currentDate.png

    # Create a list of files to delete later
    fileList="$fileList $3-$currentDate.png"

    # Build the HTML message that will be sent to the recipients, or the list of attachments
    if $includeAttachments; then
        messageAttachments="$messageAttachments -A $3-$currentDate.png"
    else
        messageBody="$messageBody <b>$4</b><br /><img src=\"$siteURL/graphs/$3-$currentDate.png\"> <br /> "
    fi
}

# See if the needed destinations are available, if not create them
if !(test -e "$backupLocation"); then
    mkdir -p $backupLocation
    chown -R $adminUser $backupLocation
    chgrp -R $adminUser $backupLocation
fi
if !(test -e "/opt/librenms/html/grpahs"); then
    mkdir /opt/librenms/html/graphs
    chown -R librenms /opt/librenms/html/graphs
    chgrp -R librenms /opt/librenms/html/graphs
fi

# Call the getGraphs function to build the message
getGraphs 21 port_bits Bandwidth "Internet bandwidth over the past 24 hours"
getGraphs 892 sensor_temperature HS-MDF-Temperature "HS server room temperature over the past 24 hours"
getGraphs 898 sensor_temperature ES-IDF3-Temperature "ES server room temperature over the past 24 hours"

# Send the email
if $includeAttachments; then
    echo "" | mail -s "$subjectLine" $messageAttachments -a "From: $sendFrom" $sendTo
else
    messageBody="$messageBody <br />This message was generated by a script running on the LibreNMS server.  <br /><br />"
    echo $messageBody | mailx -s "$(echo -e "$subjectLine\nContent-Type: text/html")" -a "From: $sendFrom" $sendTo 
fi

# Delete the temp files
rm $fileList